baseURL = "https://cwdt.github.io"
languageCode = "en-us"
title = "Building Software .Online"
theme = "hugo-bearblog"
author = "Marco "
[params]
    hideMadeWithLine = true
    dateFormat = "2006-01-02"
